deploy-dev:
  stage: deploy
  tags:
    - dev-bazigar  
  only:
     - dev 
  # environment:
  #   name: dev
  #   url: https://develop.example.com  
  
  script:
    - whoami
    - cd /home.motiontr/public_html/academy.lotusoft.in && git pull https://github.com/brajdhan/Cadence-Academy.git
    #  rsync -rvzt --exclude='.git/' --exclude='bazigar-api/.git/' -e "sshpass -f /home/gitlab-runner/bazigar.in/bazigar.pass ssh -p 1243" --progress /home/gitlab-runner/bazigar.in/bazigar-api/  bazigar@103.50.161.59:/home/bazigar/public_html/dev.bazigar.in
    # ssh -p 1243 bazigar@103.50.161.59 'cd /home/bazigar/public_html/dev.bazigar.in/; php artisan config:clear; php artisan view:clear; php artisan route:clear'
     #script for new dev2 instans
    # rsync -rvzt --exclude='.git/' -e "ssh -i /home/gitlab-runner/.ssh/id_rsa" --progress /home/gitlab-runner/bazigar.in/bazigar-api/ ubuntu@15.235.187.162:/home.motiontr/public_html/academy.lotusoft.in/dev.api.bazigar.in/
    # rsync -rvzt --exclude= '.git/' --exclude='bazigar-api/.git/' --exclude='.env.example' -e "ssh -i /home/gitlab-runner/.ssh/id_rsa" --progress /home/gitlab-runner/bazigar.in/bazigar-api/ ubuntu@15.235.187.162:/home.motiontr/public_html/academy.lotusoft.in/dev.api.bazigar.in/
    #  ssh -i /home/gitlab-runner/.ssh/id_rsa ubuntu@15.235.187.162 'cd /home.motiontr/public_html/academy.lotusoft.in/dev.api.bazigar.in/; php artisan optimize:clear; php artisan dusk'
   
    - sudo rsync -rvzt --exclude='.git/' --exclude='Cadence-Academy/.git/' -e "/home.motiontr/public_html/academy.lotusoft.in" --progress /home.motiontr/public_html/academy.lotusoft.in/  ubuntu@116.202.50.58:/home.motiontr/public_html/academy.lotusoft.in
    - https://github.com/brajdhan/Cadence-Academy.git ubuntu@116.202.50.58 'cd /home.motiontr/public_html/academy.lotusoft.in; sudo chown -R ubuntu:www-data dev.api.bazigar.in'
    - https://github.com/brajdhan/Cadence-Academy.git ubuntu@116.202.50.58 'cd /home.motiontr/public_html/academy.lotusoft.in; sudo chmod -R 775 dev.api.bazigar.in'
    - https://github.com/brajdhan/Cadence-Academy.git ubuntu@116.202.50.58 'cd /home.motiontr/public_html/academy.lotusoft.in; php artisan optimize:clear;'
